language: python:3.6

services:
      - docker

before_install:
    - docker pull xtonev/bigartm:v0.9.1 
    - docker run -d -p 127.0.0.1:80:4567 xtonev/bigartm:v0.9.1 /bin/sh -c "cd /root/TopicNet/topicnet"

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

- py.test .

