# Currently under constructuion. Requires special cube and better stage description
# This config follows a strategy described in the article
# Additive Regularization of Topic Models for Topic Selection and Sparse Factorization
# by Konstantin Vorontsov, Anna Potapenko and Alexander Plavin, Apr 2015


# Use .format(modality=modality, dataset_path=dataset_path,
# specific_topics=specific_topics, background_topics=background_topics)
# when loading the recipe to adjust for your dataset
topics:
# This strategy relies on taking excessive number of topics for initial model
    specific_topics: {specific_topics}
    background_topics: {background_topics}

regularizers:
- DecorrelatorPhiRegularizer:
    name: decorrelation_phi_{modality}
    topic_names: specific_topics
    tau: 1
    class_ids: ["{modality}"]
- SmoothSparsePhiRegularizer:
    name: smooth_phi_{modality}
    topic_names: specific_topics
    tau: 1
- SmoothSparseThetaRegularizer:
    name: sparse_theta_{modality}
    topic_names: specific_topics
    tau: 1

model: 
    dataset_path: {dataset_path}
    modalities_to_use: ['{modality}']
    main_modality: '{modality}'
#Need raising coefficients cube to exactly reproduce the experiment
stages:
- RegularizersModifierCube:
    num_iter: 8
    reg_search: mul
    regularizer_parameters:
        name: decorrelation_phi_{modality}
    selection:
        - PerplexityScore{modality} < 1.01 * MINIMUM(PerplexityScore{modality}) and SparsityPhiScore{modality} -> max
    strategy: PerplexityStrategy
    strategy_params:
        start_point: 100000
        step: 10
        max_len: 6
    tracked_score_function: PerplexityScore{modality}
    verbose: false
    use_relative_coefficients: false
- RegularizersModifierCube:
    num_iter: 8
    reg_search: add
    regularizer_parameters:
        name: smooth_phi_{modality}
    selection:
        - PerplexityScore@all < 1.01 * MINIMUM(PerplexityScore@all) and SparsityPhiScore{modality} -> max
    strategy: PerplexityStrategy
    strategy_params:
        start_point: 0.25
        step: 0.25
        max_len: 6
    tracked_score_function: PerplexityScore@all
    verbose: false
    use_relative_coefficients: false
- RegularizersModifierCube:
    num_iter: 8
    reg_search: add
    regularizer_parameters:
        name: sparse_theta_{modality}
    selection:
        - PerplexityScore@all < 1.01 * MINIMUM(PerplexityScore@all) and SparsityPhiScore{modality} -> max
    strategy: PerplexityStrategy
    strategy_params:
        start_point: -0.5
        step: -0.5
        max_len: 6
    tracked_score_function: PerplexityScore@all
    verbose: false
    use_relative_coefficients: false